/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/words/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get 3 random words for drawing */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of 3 random words and a verification token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WordsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get personal stats for the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User statistics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sketches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all sketches with anti-spoiler word hiding */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of sketches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackendSketch"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new sketch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Sketch details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSketchRequest"];
                };
            };
            responses: {
                /** @description Sketch created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackendSketch"];
                    };
                };
                /** @description Missing parameter or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - token does not belong to authenticated user */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Word not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sketches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get details of a single sketch */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sketch details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SketchDetail"];
                    };
                };
                /** @description Sketch not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboards/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get ranking of best players based on correctly guessed words */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player leaderboard retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlayerRanking"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboards/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get ranking of best artists based on sketch guess accuracy */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Artist leaderboard retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtistRanking"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Authenticate user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User credentials to authenticate */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCredentials"];
                };
            };
            responses: {
                /** @description User authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Missing or invalid credentials */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new user account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description User registration details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCredentials"];
                };
            };
            responses: {
                /** @description User created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignupResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Username already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sketches/{id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit a guess for a sketch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            /** @description Guess attempt details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttemptRequest"];
                };
            };
            responses: {
                /** @description Attempt registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptResponse"];
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Action forbidden (e.g. self guess, no attempts left) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Sketch not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserCredentials: {
            /** @example Kyle */
            username: string;
            /** @example p4ssw0rd */
            password: string;
        };
        LoginResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token: string;
        };
        SignupResponse: {
            /** @example Kyle */
            username: string;
            /** @example User created successfully */
            message?: string;
        };
        WordChoice: {
            /** @example 1 */
            id_word: number;
            /** @example gatto */
            text: string;
        };
        WordsResponse: {
            words: components["schemas"]["WordChoice"][];
            /** @example eyJhbGciOiJIUzI1NiIsIn... */
            token: string;
        };
        BackendAttempt: {
            /** @example cane */
            guess: string;
            /** @example false */
            is_correct: boolean;
            /** Format: date-time */
            timestamp?: string;
        };
        BackendSketch: {
            /** @example 1 */
            id_sketch: number;
            /** @example 2 */
            id_user?: number;
            /** @example 5 */
            id_word?: number;
            /** @example {"objects":[]} */
            path: string;
            /** Format: date-time */
            timestamp?: string;
            /** Format: date-time */
            createdAt?: string;
            User: {
                /** @example marco */
                username: string;
            };
            Word?: {
                /** @example gatto */
                text?: string;
            };
            user_attempts?: components["schemas"]["BackendAttempt"][];
        };
        SketchDetail: {
            /** @example 1 */
            id_sketch: number;
            /** @example {"objects":[]} */
            path: string;
            /** Format: date-time */
            createdAt?: string;
            User: {
                /** @example marco */
                username: string;
            };
            Word?: {
                /** @example gatto */
                text?: string;
            };
            user_attempts?: components["schemas"]["BackendAttempt"][];
        };
        CreateSketchRequest: {
            /** @example 1 */
            id_word: number;
            /** @example {"objects":[]} */
            path: string;
            /** @example eyJhbGciOiJIUzI1NiIsIn... */
            words_token: string;
        };
        CreateAttemptRequest: {
            /** @example gatto */
            guess: string;
        };
        AttemptResponse: {
            /** @example 12 */
            id_attempt?: number;
            /** @example gatto */
            guess?: string;
            /** @example true */
            is_correct: boolean;
            /** @example 9 */
            attempts_remaining: number;
            /** @example gatto */
            solution?: string;
        };
        PlayerRanking: {
            /** @example 1 */
            id_user: number;
            /** @example marco */
            username: string;
            /** @example 15 */
            score: number;
        };
        ArtistRanking: {
            /** @example 1 */
            id_user: number;
            /** @example marco */
            username: string;
            /** @example 85 */
            percentage: number;
            /** @example 20 */
            total_attempts: number;
            /** @example 17 */
            successful_attempts: number;
            /** @example 5 */
            sketches_count: number;
        };
        UserStats: {
            /** @example 3 */
            sketches_count: number;
            /** @example 12 */
            guessed_count: number;
            /** @example 25 */
            attempts_count: number;
            /** @example 1 */
            unguessed_count: number;
        };
        ErrorResponse: {
            /** @example An error occurred */
            error: string;
            /** @example 400 */
            code?: number;
            /** @example Invalid input provided */
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
